### ISSUE TITLE
New domain and mail

### ISSUE THREAD

**Issue by tistatos** [klaseskilson/vattentornet#113]
The board members seem to have issues with the mail connected to domain provider One. They want to look at alternative providers and new mail system.

Maybe use Gmail apps? downside is the limited inbox space
What is a better domain provider?

**Comment by tistatos** [comment]
Doesn't seem like this is a priority...

**Comment by klaseskilson** [comment]
I guess we can close this then?

**Comment by tistatos** [comment]
Yepp, Dennis mentioned this but doesnt seem as it has been a problem for them in general
