### ISSUE TITLE
Make news index sortable

### ISSUE THREAD

**Issue by tistatos** [klaseskilson/vattentornet#114]
As admin I would like to be able to sort news after for instance, date

Perhaps its overkill to have it sortable? But then, how about descending sorting of news i.e newest first?

**Comment by klaseskilson** [comment]
@tistatos, can this be closed now that #120 is merged?

**Comment by tistatos** [comment]
I guess so. I never learn but i assume it will only automagically close when merged to master?

**Comment by klaseskilson** [comment]
Nope, you need to write something like `closes #114` in a commit or PR message for it to work that way. [Read here!](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by tistatos** [comment]
But I did do that in #120 :/

**Comment by klaseskilson** [comment]
Weeeeeird, since it doesn't say that above. It only says so about #118. But let's wait and see if it works then. Great work! 👍
