### ISSUE TITLE
Change body font

### ISSUE THREAD

**Issue by klaseskilson** [klaseskilson/vattentornet#125]
[Fauna One](https://fonts.google.com/specimen/Fauna+One) that we use now doesn't even support bold text.

I suggest one of 

- https://fonts.google.com/specimen/Neuton
- https://fonts.google.com/specimen/Arvo
- ~~https://fonts.google.com/specimen/Roboto+Slab~~ (no italics)
- https://fonts.google.com/specimen/Droid+Serif

**Comment by tistatos** [comment]
I prefer Neuton

**Comment by klaseskilson** [comment]
I like Neuton too, but I don't think it is suitable for body text when I look closer, I think the readability isn't good enough. I prefer Droid Serif, I think it looks the best on a larger text mass tbh.

**Comment by klaseskilson** [comment]
Fauna One: 

<img width="1680" alt="screen shot 2016-09-20 at 09 52 07" src="https://cloud.githubusercontent.com/assets/1674076/18661897/2c9d69ca-7f18-11e6-9624-ad4b966f3b55.png">

Droid Serif:

<img width="1680" alt="screen shot 2016-09-20 at 09 51 42" src="https://cloud.githubusercontent.com/assets/1674076/18661898/2ca1b93a-7f18-11e6-89a8-0cad2196f071.png">

Arvo (with adjusted body font size, `font-size: 1.1em;` on `.main-content .pane`): 

<img width="1680" alt="screen shot 2016-09-20 at 09 59 31" src="https://cloud.githubusercontent.com/assets/1674076/18662097/16bcfb74-7f19-11e6-9442-8ebe53b5eca2.png">


Roboto Slab (with adjusted body font size, `font-size: 1.1em;` on `.main-content .pane`): 

<img width="1680" alt="screen shot 2016-09-20 at 10 12 16" src="https://cloud.githubusercontent.com/assets/1674076/18662467/ca29c768-7f1a-11e6-9bf6-6e819b164621.png">

**Comment by klaseskilson** [comment]
@danielronnkvist @tistatos ☝️ thoughts?

**Comment by danielronnkvist** [comment]
I like Droid Serif and Arvo in the examples above

**Comment by klaseskilson** [comment]
Those are my favourites too. Arvo's looks especially, but it is perhaps a bit too bold?

**Comment by klaseskilson** [comment]
Forgot Neuton! (`font-size: 1.2em;` on `.main-content .pane`)

<img width="1680" alt="screen shot 2016-09-20 at 17 53 28" src="https://cloud.githubusercontent.com/assets/1674076/18678105/4703aad4-7f5b-11e6-8306-0dcba9d1c74e.png">

**Comment by klaseskilson** [comment]
Cast you votes!

👍 : Fauna one (unchanged)
👎 : Droid Serif
😄 : Arvo
🎉 : Roboto Slab
😕 : Neuton

**Comment by klaseskilson** [comment]
Droid Serif it is then!
