### ISSUE TITLE
Booking date uses american formatting

### ISSUE THREAD

**Issue by tistatos** [klaseskilson/vattentornet#147]
When you want to create a booking, the date uses american mm/dd/yyyy formatting. Should we use Swedish format instead?

**Comment by klaseskilson** [comment]
Yes we should!

**Comment by klaseskilson** [comment]
@tistatos Do you mean the date picker for this btw? I think that might be client-specific?

**Comment by tistatos** [comment]
![image](https://cloud.githubusercontent.com/assets/2827554/18689798/4b44db42-7f8b-11e6-98ad-df6932bb0b65.png)

This is how booking form looks for me

**Comment by klaseskilson** [comment]
I think that is Chrome's fault. The placeholder we have does not look like that: https://github.com/klaseskilson/vattentornet/blob/d638667f39b68885dda54f279be6b1c8cfa6581b/app/views/bookings/_form.html.erb#L40

**Comment by klaseskilson** [comment]
I'm closing this as there is nothing we can do about it.

**Comment by tistatos** [comment]
:+1: correct formatting on firefox
