### ISSUE TITLE
Interval booking for the 10th every month broken

### ISSUE THREAD

**Issue by klaseskilson** [klaseskilson/vattentornet#58]
When there is an interval booking that overlaps the 10th of each month, that is not displayed. Sounds like there is a messy modulus operator somewhere in the interval booking?

<img width="990" alt="screen shot 2015-11-03 at 13 10 24" src="https://cloud.githubusercontent.com/assets/1674076/10907650/4aec3896-822c-11e5-8056-f683a30da6dd.png">

**Comment by danielronnkvist** [comment]
I can take a look.

**Comment by tistatos** [comment]
Could the issue be [here]?(https://github.com/klaseskilson/vattentornet/blob/master/app/assets/javascripts/angular/controller/calendarCtrl.js#L27)

when j = 11 the loopdate is YYYY-MM-011
why is it j-1 ?

**Comment by klaseskilson** [comment]
I'm not sure why it is `j-1`, since making it just `j` seems to solve it (without any side effects that I can notice).
